### ISSUE TITLE
weekly tasks & progress

### ISSUE THREAD

**Issue by dunland** [quarree100/qScope_frontend#24]
- [x] slider position outside of grid
- [x] slider controls → cspy→q100_viz→infoscreen
- [x] 4-pin-LED-power + **runde** 2fach-Pinheader

**Comment by dunland** [comment]
# KW 52 / später
- [ ] lasert @cqx931 noch einen Slider + ein Grid

**Comment by dunland** [comment]
# 2022-KW1
@cqx931 :
- [ ] Slider-Bereich einfärben je nach ausgewähltem Slider-Parameter
- [ ] Infoscreen: Statusanzeige von Strom/Gas-Anbieter, Wärmenetzanschluss, Ausbau Technologie?

@dunland:
- [ ] Besorgung LED-Stromquelle mit 4-Pin-Anschluss

**Comment by cqx931** [comment]
- [ ] CO2-Emission

- [ ] Stromverbrauch (erstmal generisch [0...1000]) → schlussendlich wohl anonym/randomisiert

- [ ] Strom/Gas (herkömmlich/grau-grün/grün)
- [ ] Wärmenetzanschluss (nein/ja)
- [ ] Investition (Stufe 1 / Stufe 2 / Stufe 3 inkl. Wärmenetzanschluss / Stufe 4 inkl. Wärmenetzanschluss)

**Comment by dunland** [comment]
auf welchem Branch hast du das implementiert?

**Comment by dunland** [comment]
sieht gut aus! :top:

**Comment by dunland** [comment]
@dunland:
- [ ] ABM verstehen + selber nochmal überlegen, was auf den Infoscreen gehört, also **Visualisierungskonzepte → Mockup infoscreen**

## KW 03
@cqx931:
- [ ] q100_info an 4K-Monitor testen
- [ ] infoscreen: metadaten ergänzen, falls noch welche fehlen
- [ ] akkumuliertes CO2 (Cluster) anzeigen

**Comment by dunland** [comment]
Infoscreen and frontend should be programmed according to this scheme:

![image](https://user-images.githubusercontent.com/23742320/150114581-8a999efd-a032-4e11-8f5b-789f85ee5860.png)

**Comment by cqx931** [comment]
https://github.com/cqx931/q100_info/commit/636e30c9bb29643acc77efd690959c6dba9f070

Um in den neuen Simulationsmodus zu sehen, drück die Leertaste.  Für Quatier Simulation, habe ich erst mal ein paar "fake data" benutzt.

<img width="1400" alt="Screenshot 2022-01-29 at 16 17 42" src="https://user-images.githubusercontent.com/3056154/151666450-95bca99b-90a5-4210-aab5-ec76dab21560.png">
8

**Comment by dunland** [comment]
mhm, kannst du mir dafür vielleicht noch deine mockup daten zukommen lassen? Finde es nicht ganz einfach das nachzuvollziehen ohne die Inputdaten. das wäre sehr cool!

**Comment by dunland** [comment]
hey @kazux2 , here is a summary of some tasks for you:

- [ ] get qScope_infoscreen and qScope_frontend to run!
- [ ] understand basics of node.js and d3.js
- [ ] dive into the Code of the infoscreen and understand what's going on. Please add Code documentation along the way.. the Code is quite spaghetti, and it would help a lot if the different sections were marked.
- [ ] more specifically, take care of the [line chart implementations](https://github.com/quarree100/qScope_infoscreen/issues/1) in d3.

**Comment by dunland** [comment]
## Questionnaire Mode
- infoscreen layout: 4 columns? / some loading screen ("X% questions answered")... @dunland @lwinkeler @kazux2 

## Input Scenarios

1. [x] position the images
    - [x] dynamically resizable by canvas_size
    - later: dynamically resizable by grid size? should be e.g. 0.81 * canvas_width
2. [x] image: toggle selection
3. [x] UI: select by placing token on grid
    - [x] select by relative grid position? (1/2 vs 2/2)
4. [ ] what should infoscreen look like?
    - [x] send picked scenario handler to infoscreen ['A', 'B', 'C', 'D']
    - display more than just the variable names: what do these values imply @lwinkeler?
    - later: what should UI look like? → add to projection
5. [ ] display details on infoscreen @kazux2 
6. how to leave this mode?
    - [x] global "ready" token..

- TODOS:
    - [ ] rename "environment" -> "scenarios" @dunland 
    - [ ] update scenario csvs @dunland 

## Input Households

1. Interaction Possibilities: @lwinkeler 
    - set refurbishment
    - (set electricity supplier)
    - set heat supplier
    - (set special environmental engagement)
    - token effect range
    - ready button
2. Infoscreen:
    - [ ] Display the selected scenario (human-readable short name) somewhere @kazux2 @lwinkeler 
    - [ ] layout concept: how many buildings possible per column? need of aggregated/average values? @kazux2 @dunland 
    - [ ] layout realization: display selected buildings column-wise (one column for each user) @kazux2 
3. Multi-User Mode:
    - [ ] multiple valid IDs @dunland 
    
## Simulation Mode

- [ ] select scenario data → use it to compose GAMA-dataframe! ... use, for example `scenario_A.csv`
- [ ] making GAMA run via headless mode @dunland
1. run gama, wait for it to finish
2. receive / read data
3. pass variables to infoscreen, enter data view

## Data View

2022-05-30

- [x] Infoscreen: enter data view mode
- [ ] example: heat_connection as Pie-Chart @kazux2  (use gama-generated tables by @lwinkeler)
- [ ] example: heat_connection and emissions as f(t) @kazux2

**Comment by lwinkeler** [comment]
> externalize questionnaire to another online-document

First version for testing has been created.

Accessible under:
https://www.surveylegend.com/s/486i

Connected QR-Code:
![frame](https://user-images.githubusercontent.com/70899694/172335613-b8f9df49-8935-48ee-bcba-78e8bcbeba95.png)

**Comment by dunland** [comment]
## 2022-KW29
**TODO @dunland **

- [ ] ABM push überprüfen
- [ ] send sum of connections per group
- [ ] wrap "data_view_data" around json struct + get rid of [ ] in json
- [ ] combine two messags sent for dataview

**Comment by dunland** [comment]
# 2022-KW32

## simulation-mode
- [ ] start new process (using multiprocessing!) for simulation; display "simulation is running"

## infoscreen
- [ ] Umsetzung Layout von R+E
    - [ ] Prüfen eingegangener Vorschläge von Nele:
        - [ ] Definition unserer Workshop-Ziele
        - [ ] Decken sich diese mit den Vorschlägen?

**Comment by dunland** [comment]
# KW 33
## interaction @dunland
- [x] lines that show heat grid connection
- [ ] global slider for game stages and modes
- [ ] add tooltips on infoscreen https://github.com/quarree100/qScope_infoscreen/issues/24
- [ ] display slider naming, hints and value thresholds

**Comment by dunland** [comment]
#2022-KW34
- [ ] Kategorisierung der Gebäude nach ['age', 'energy_source', 'area']

**Comment by dunland** [comment]
# 2022-KW35


## Interaction
- [x] Interaction mode: layout infoscreen (approximately same as individual data view)
- [ ] interaction mode: include clustered energy data of building
- [x] time line with mode selectors instead of slider for game mode
- [ ] infoscreen: coloring buildings? (currently via environmental_engagement...)
- [ ] display scenario: Finanzierungskonzepte https://github.com/quarree100/q100_abm/issues/88

## Ergebnisdarstellung
- [ ] ABM-Feature: tranquilize agents ASAP, Ende KW35 @lwinkeler 
    - [ ] Quartiersdaten: worst case / best case Szenarien vorrechnen: verschiedene Anschlussquoten
- [x] ABM: building-specific energy prices https://github.com/quarree100/q100_abm/issues/82 
    - [x] → individual data view: create graphs via matplotlib 
    - [x] → individual data view: send graphs to infoscreen
- [ ] switch between modes: individual and total data view
- [ ] total data view: comparative display of individual energy costs with Anschlusszeitpunkt

### individual data view
- [ ] environmental_engagement: bool vs float?
- [ ] round-based graph layers? → should be implemented already, check if it works!
- [ ] display cluster_size
- [ ] color energy_prices according to type analogously to scenario_energy_prices_data
- [ ] cumulative costs instead of monthly costs?
- [ ] show time of connection in graph

### ABM + UI
- [ ] discuss `environmental_engagement` https://github.com/quarree100/qScope_infoscreen/issues/23#issuecomment-1229962529

### Einführung
- [ ] create Introduction mode
- [ ] Überblick-Einstellung auf Infoscreen: zeige alle Stellschrauben / Parameter; hebe jene hervor, die wir ändern werden

## Weiteres

- [ ] https://github.com/quarree100/q100_abm/issues/83
- [ ] make graphs more comprehensive: 
    - [ ] monthly costs rather than ct/kWh
    - [ ] check all units! @lwinkeler @dunland sind die Einheiten in den Graphen alle korrekt?
    - [ ] add past energy costs (pre-2020) to graphs
- [ ] slider: show thresholds for non-bools

**Comment by dunland** [comment]
#2022-KW37

## Interaction

- [ ] infoscreen: highightling selected decsion feature + frame around infoscreen in color of current round + coloring buildings according to connection status @kazux2  https://github.com/quarree100/qScope_infoscreen/issues/27
- [ ] https://github.com/quarree100/qScope_frontend/issues/34

## Results:

- [ ] Quartiersdaten: worst case / best case Szenarien vorrechnen: verschiedene Anschlussquoten
- [ ] **Ergebnisse überprüfen und validieren!!!**
- [ ] make graphs more comprehensive: https://github.com/quarree100/qScope_frontend/issues/39

### individual data view:

- [ ] show buildings ø-consumption data
- [ ] round-based graph layers? → pass decisions of round as string to graph legend
- [ ] display cluster_size @kazux2 

## Extensions

- [ ] display scenario: Finanzierungskonzepte https://github.com/quarree100/q100_abm/issues/88
- [ ] frame around infoscreen for iteration round: https://github.com/quarree100/qScope_infoscreen/issues/28
- [ ] Anschlusszeitpunkt: https://github.com/quarree100/q100_abm/issues/83
- [ ] slider: show thresholds for non-bools
- [ ] discuss `environmental_engagement` https://github.com/quarree100/qScope_infoscreen/issues/23#issuecomment-1229962529 (bool vs float vs string)

### Einführung

- [ ] create Introduction mode
- [ ] Überblick-Einstellung auf Infoscreen: zeige alle Stellschrauben / Parameter; hebe jene hervor, die wir ändern werden

**Comment by dunland** [comment]
# 2022-KW43

## Interaction

- [ ] https://github.com/quarree100/qScope_frontend/issues/34
- [ ] https://github.com/quarree100/qScope_frontend/issues/41

## Results:

- [ ] Quartiersdaten: worst case / best case Szenarien vorrechnen: verschiedene Anschlussquoten
- [ ] **Ergebnisse überprüfen und validieren!!!** https://github.com/quarree100/q100_abm/issues/76
- [ ] make graphs more comprehensive: https://github.com/quarree100/qScope_frontend/issues/39

### individual data view:

- [ ] https://github.com/quarree100/q100_abm/issues/76#issuecomment-1262242033: Zeitreihen für unveränderte Bestandsgebäude

## UI

- [ ] Graphen: deutlichere Farben pro Runde
- [ ] Graphen: gleiches ylabel min([ymin]), max([ymax])

## Hardware

- [ ] color building tokens according to groups
- [ ] test interaction/light conditions with many people around table

________________

## Extensions

- [ ] display scenario: Finanzierungskonzepte https://github.com/quarree100/q100_abm/issues/88
- [ ] frame around infoscreen for iteration round: https://github.com/quarree100/qScope_infoscreen/issues/28
- [ ] add tooltips on infoscreen https://github.com/quarree100/qScope_infoscreen/issues/24
- [ ] https://github.com/quarree100/qScope_frontend/issues/30#issuecomment-1225686374
- [ ] Quartiersdarstellung aus GAMA auf Frontend anzeigen?
- [ ] Zeitverläufe vor 2020 ? Achtung: Berücksichtigung Inflationsrate, ....
- [ ] show share of different energy_sources in neighborhood (gas, oil, q100); e.g. before/after simulation https://github.com/quarree100/qScope_infoscreen/issues/23#issuecomment-1234246567

**Comment by dunland** [comment]
## Updates
@lwinkeler weil du dir bei der Übergabe Notizen gemacht hast, die hiermit veraltet sind:

**since** https://github.com/quarree100/qScope_frontend/commit/a684c717a21b492f22c3a35bd9376131972aa239: 
- keys for corner point selection in calibration mode are 1,2,3,4 (not TAB)
- game Modes can be switched via 0,9,8,7
- flag `--refurb [INT]` oder `-r [INT]` ist jetzt `int` mit Jahreszahl der Sanierung (merke: für **alle** vorausgewählten Gebäude)
